"""
code_agent.py — Code role for self-improving agent system.
========================================================

DESIGN:
  - Takes accepted proposals from Plan role as input
  - Generates code patches/diffs (deterministic for now, no LLM)
  - Does NOT apply code directly - Test role validates first
  - All code changes written to change board as change_type="code_change"
  - Fail-closed: invalid input or generation failures abort the pipeline

CONTRACT:
  Input: PipelineContext with plan_proposals
  Output: list of CodeChange objects for the pipeline context
  
  Each CodeChange becomes a change board entry that Test role can consume.

KEDB considerations:
  - Model may fabricate code -> constrain at parser boundary (future)
  - Empty input -> fail-closed (no code to generate)
  - Code never applied directly (AGENTS.md implicit: changes flow through board)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backbone import Backbone
    from pipeline import PipelineContext
    from plan_agent import Proposal


# ---------------------------------------------------------------- constants

# Code change types
CODE_CHANGE_TYPES = (
    "new_file",       # Create a new file
    "modify_file",    # Modify an existing file
    "delete_file",    # Delete a file
    "refactor",       # Structural changes across files
    "config_change",  # Configuration file changes
    "dependency",      # Dependency additions/updates
)

# Default file templates by change type
FILE_TEMPLATES = {
    "new_file": """# {file_name}
# Generated by self-improving agent system
# Proposal: {proposal_summary}

{content}
""",
    "modify_file": """# {file_name}
# Modified by self-improving agent system
# Proposal: {proposal_summary}
# Original content preserved, modifications applied

{content}
""",
    "config_change": """# Configuration for {component}
# Modified by self-improving agent system
# Proposal: {proposal_summary}

{content}
""",
}


@dataclass
class CodeChange:
    """A code change generated by the Code role."""
    # What to change
    change_type: str  # new_file, modify_file, delete_file, refactor, config_change, dependency
    file_path: str
    
    # The change content
    content: str = ""
    old_content: str = ""  # For modify_file, the original content
    diff: str = ""  # Unified diff format when applicable
    
    # Why (from Plan proposal)
    proposal_id: str | None = None
    proposal_summary: str = ""
    proposal_type: str = ""
    
    # Metadata
    priority: float = 0.0
    estimated_lines: int = 0
    change_id: int | None = None  # change board ID
    
    def to_change_payload(self) -> dict:
        """Convert to payload format for change board."""
        return {
            "change_type": self.change_type,
            "file_path": self.file_path,
            "content": self.content[:10000] if self.content else "",  # Limit size in payload
            "old_content": self.old_content[:10000] if self.old_content else "",
            "diff": self.diff[:5000] if self.diff else "",
            "proposal_id": self.proposal_id,
            "proposal_summary": self.proposal_summary,
            "proposal_type": self.proposal_type,
            "priority": self.priority,
            "estimated_lines": self.estimated_lines,
        }


# ---------------------------------------------------------------- code generation utilities

def generate_file_path(proposal_summary: str, change_type: str) -> str:
    """Generate a plausible file path based on proposal summary and change type."""
    import re
    
    # Extract keywords from summary
    keywords = re.findall(r'\b([a-z_][a-z0-9_]*)\b', proposal_summary.lower())
    
    # Map keywords to common file patterns
    if change_type == "new_file" or change_type == "modify_file":
        if any(kw in keywords for kw in ['test', 'spec']):
            return f"tests/test_{keywords[0] if keywords else 'new'}.py"
        elif any(kw in keywords for kw in ['config', 'setting', 'yaml', 'json']):
            return f"config/{keywords[0] if keywords else 'new'}.yaml"
        elif any(kw in keywords for kw in ['agent', 'role', 'pipeline']):
            return f"src/{keywords[0] if keywords else 'new'}_agent.py"
        elif any(kw in keywords for kw in ['util', 'helper', 'tool']):
            return f"src/utils/{keywords[0] if keywords else 'new'}.py"
        else:
            return f"src/{keywords[0] if keywords else 'new'}.py"
    
    elif change_type == "dependency":
        return "requirements.txt"
    
    elif change_type == "config_change":
        return "config/settings.yaml"
    
    else:
        return f"src/{keywords[0] if keywords else 'change'}.py"


def generate_content(proposal, change_type: str, file_path: str) -> str:
    """Generate code content based on proposal and change type."""
    import json
    
    # Extract fields from proposal (handle both dict and Proposal objects)
    if isinstance(proposal, dict):
        summary = proposal.get("summary", "")
        description = proposal.get("description", "")
        evidence = proposal.get("evidence", "")
        source = proposal.get("source", "")
    else:
        summary = getattr(proposal, "summary", "")
        description = getattr(proposal, "description", "")
        evidence = getattr(proposal, "evidence", "")
        source = getattr(proposal, "source", "")
    
    # Determine content based on change type
    if change_type == "new_file":
        # Generate a new Python module
        class_name = file_path.replace(".py", "").replace("/", "_").replace("-", "_")
        doc_string = description[:100].replace('"""', '\"\"\"')
        content = f"""\
\"\"\"{summary}

Generated by self-improving agent system.
Source: {source}
Evidence: {evidence[:100]}
\"\"\"

class {class_name}:
    \"\"\"{doc_string}\"\"\"
    
    def __init__(self):
        # TODO: Implement based on proposal
        pass
    
    def run(self):
        # TODO: Implement based on proposal
        pass
"""
        return content
    
    elif change_type == "modify_file":
        # Generate a modification comment
        content = f"""# Modification by self-improving agent system
# Proposal: {summary}
# Description: {description[:100]}
# Source: {source}

# [TODO: Apply actual modifications here]
"""
        return content
    
    elif change_type == "dependency":
        # Generate a requirements entry
        # Extract package name from evidence or source
        import re
        match = re.search(r'(?:package|lib|module)[:\s]*([a-z0-9_-]+)', evidence.lower())
        package = match.group(1) if match else "new-package"
        return f"{package}>=1.0.0  # {summary}"
    
    elif change_type == "config_change":
        # Generate YAML config
        config_name = file_path.replace(".yaml", "").replace(".yml", "").replace("config/", "")
        return f"""# {config_name} configuration
# Modified by self-improving agent system
# Proposal: {summary}

{config_name}:
  enabled: true
  # TODO: Add specific configuration based on proposal
"""
    
    else:
        # Generic code change
        return f"""# Code change by self-improving agent system
# Proposal: {summary}
# Description: {description[:100]}
"""


def generate_diff(old_content: str, new_content: str, file_path: str) -> str:
    """Generate a unified diff between old and new content."""
    import difflib
    
    old_lines = old_content.splitlines(keepends=True)
    new_lines = new_content.splitlines(keepends=True)
    
    diff = difflib.unified_diff(
        old_lines, new_lines,
        fromfile=f"a/{file_path}",
        tofile=f"b/{file_path}",
    )
    
    return "".join(diff)


# ---------------------------------------------------------------- mapping from proposal to code changes

def map_proposal_to_changes(proposal) -> list[dict]:
    """Map a proposal to one or more code change specifications.
    
    Returns list of dicts with keys: change_type, file_path, content, etc.
    """
    # Extract fields from proposal (handle both dict and Proposal objects)
    if isinstance(proposal, dict):
        change_type = proposal.get("change_type", "feature")
        summary = proposal.get("summary", "")
        description = proposal.get("description", "")
        source = proposal.get("source", "")
        evidence = proposal.get("evidence", "")
        priority = proposal.get("priority", 0)
        effort = proposal.get("estimated_effort", 5)
    else:
        change_type = getattr(proposal, "change_type", "feature")
        summary = getattr(proposal, "summary", "")
        description = getattr(proposal, "description", "")
        source = getattr(proposal, "source", "")
        evidence = getattr(proposal, "evidence", "")
        priority = getattr(proposal, "priority", 0)
        effort = getattr(proposal, "estimated_effort", 5)
    
    # Map proposal change_type to code change types
    code_changes = []
    
    if change_type in ("feature", "improvement_proposal"):
        # Features typically require new or modified files
        file_path = generate_file_path(summary, "new_file")
        content = generate_content(proposal, "new_file", file_path)
        estimated_lines = max(10, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "new_file",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
        
        # May also need a test file
        test_path = generate_file_path(summary + " test", "new_file")
        if not test_path.endswith("_test.py") and not test_path.endswith("test_") :
            test_path = test_path.replace(".py", "_test.py")
        test_content = f"""# Tests for {file_path}
# Generated by self-improving agent system

def test_basic():
    # TODO: Implement tests based on proposal
    assert True
"""
        code_changes.append({
            "change_type": "new_file",
            "file_path": test_path,
            "content": test_content,
            "priority": priority - 0.5,  # Slightly lower priority
            "estimated_lines": len(test_content.splitlines()),
        })
    
    elif change_type == "bugfix":
        # Bug fixes typically modify existing files
        file_path = generate_file_path(summary, "modify_file")
        content = generate_content(proposal, "modify_file", file_path)
        estimated_lines = max(5, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "modify_file",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
    
    elif change_type == "refactor":
        # Refactoring may affect multiple files
        # Generate changes for 2-3 files
        for i in range(2):
            file_path = generate_file_path(f"{summary} part {i+1}", "refactor")
            content = generate_content(proposal, "refactor", file_path)
            estimated_lines = max(15, len(content.splitlines()))
            
            code_changes.append({
                "change_type": "modify_file",
                "file_path": file_path,
                "content": content,
                "priority": priority,
                "estimated_lines": estimated_lines,
            })
    
    elif change_type == "test":
        # Test improvements
        file_path = generate_file_path(summary, "new_file")
        if not file_path.endswith("_test.py"):
            file_path = file_path.replace(".py", "_test.py")
        content = generate_content(proposal, "new_file", file_path)
        estimated_lines = max(10, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "new_file",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
    
    elif change_type == "docs":
        # Documentation changes
        file_path = generate_file_path(summary, "new_file").replace(".py", ".md")
        content = f"""# Documentation: {summary}

{description}

---
*Generated by self-improving agent system*
*Source: {source}*
"""
        estimated_lines = max(10, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "new_file",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
    
    elif change_type == "infrastructure":
        # Infrastructure changes (config, dependencies, etc.)
        # Add a config change
        file_path = "config/settings.yaml"
        content = generate_content(proposal, "config_change", file_path)
        estimated_lines = max(5, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "config_change",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
        
        # Add a dependency change
        file_path = "requirements.txt"
        content = generate_content(proposal, "dependency", file_path)
        estimated_lines = 1
        
        code_changes.append({
            "change_type": "dependency",
            "file_path": file_path,
            "content": content,
            "priority": priority - 0.5,
            "estimated_lines": estimated_lines,
        })
    
    elif change_type == "research":
        # Research typically produces documentation or example code
        file_path = generate_file_path(summary, "new_file").replace(".py", "_research.md")
        content = f"""# Research: {summary}

## Findings

{description}

## Source
{source}

## Evidence
{evidence}

---
*Generated by self-improving agent system*
"""
        estimated_lines = max(20, len(content.splitlines()))
        
        code_changes.append({
            "change_type": "new_file",
            "file_path": file_path,
            "content": content,
            "priority": priority,
            "estimated_lines": estimated_lines,
        })
    
    return code_changes


# ---------------------------------------------------------------- the agent

class CodeAgent:
    """Code role: generates code changes from accepted proposals.
    
    All actions flow through the Backbone's audited API.
    Fail-closed: invalid input or generation failures abort the pipeline.
    Does NOT apply code directly - Test role validates first.
    """

    def __init__(self, bb: "Backbone", role: str = "code"):
        self.bb = bb
        self.role = role
        self.model = None  # Code role uses deterministic generation for now

    def run(self, job_id: str, context: "PipelineContext") -> list[CodeChange]:
        """Generate code changes from Plan proposals.
        
        Args:
            job_id: The job identifier
            context: PipelineContext containing plan_proposals
            
        Returns:
            List of CodeChange objects
            
        Raises:
            RuntimeError: If no valid proposals or generation fails
        """
        import hashlib
        
        # 1. Goal-drift guard: spec re-injected verbatim at handoff
        spec = self.bb.get_spec_verbatim(job_id)
        
        # 2. Extract proposals from context
        proposals = context.plan_proposals if context else []
        
        # 3. Fail-closed: no proposals = no code to generate
        if not proposals:
            self.bb.trace("tool_call", self.role, {
                "tool": "code_validation",
                "status": "empty_input_abort",
                "detail": "no plan proposals to generate code from — aborting",
            }, job_id=job_id)
            raise RuntimeError("Code role: no plan proposals to generate code from")
        
        # 4. Trace the code generation invocation
        self.bb.trace("role_invoke", self.role, {
            "input_type": "plan_proposals",
            "input_count": len(proposals),
            "spec_sha256_tail": hashlib.sha256(spec.encode()).hexdigest()[-12:],
        }, job_id=job_id)
        
        # 5. Generate code changes from each proposal
        all_changes: list[CodeChange] = []
        for i, prop in enumerate(proposals):
            # Map proposal to code changes
            change_specs = map_proposal_to_changes(prop)
            
            for j, spec in enumerate(change_specs):
                # Create a unique proposal_id for this change
                proposal_id = f"prop-{i}-change-{j}"
                if isinstance(prop, dict):
                    proposal_summary = prop.get("summary", f"Proposal {i}")
                    proposal_type = prop.get("change_type", "feature")
                else:
                    proposal_summary = getattr(prop, "summary", f"Proposal {i}")
                    proposal_type = getattr(prop, "change_type", "feature")
                
                change = CodeChange(
                    change_type=spec["change_type"],
                    file_path=spec["file_path"],
                    content=spec["content"],
                    proposal_id=proposal_id,
                    proposal_summary=proposal_summary,
                    proposal_type=proposal_type,
                    priority=spec.get("priority", 0),
                    estimated_lines=spec.get("estimated_lines", 0),
                )
                all_changes.append(change)
                
                # Trace each generation
                self.bb.trace("tool_call", self.role, {
                    "tool": "code_generation",
                    "proposal_idx": i,
                    "change_idx": j,
                    "change_type": spec["change_type"],
                    "file_path": spec["file_path"],
                    "estimated_lines": spec.get("estimated_lines", 0),
                }, job_id=job_id)
        
        # 6. Fail-closed: if no changes generated from valid proposals
        if not all_changes:
            self.bb.trace("tool_call", self.role, {
                "tool": "code_validation",
                "status": "no_changes_abort",
                "detail": f"{len(proposals)} proposals yielded 0 code changes",
            }, job_id=job_id)
            raise RuntimeError(f"Code role: {len(proposals)} proposals yielded 0 code changes")
        
        # 7. Sort changes by priority (descending)
        all_changes.sort(key=lambda c: c.priority, reverse=True)
        
        # 8. Write all code changes to the change board
        for change in all_changes:
            change_id = self.bb.propose_change(
                job_id, self.role, "code_change",
                f"{change.change_type}: {change.file_path}",
                change.to_change_payload(),
                tier=3,
            )
            change.change_id = change_id
        
        # 9. Trace completion
        self.bb.trace("model_response", self.role, {
            "changes_generated": len(all_changes),
            "total_lines_estimated": sum(c.estimated_lines for c in all_changes),
            "files_affected": len(set(c.file_path for c in all_changes)),
        }, job_id=job_id)
        
        return all_changes


if __name__ == "__main__":
    # Quick smoke test
    from pathlib import Path
    from backbone import Backbone
    from pipeline import PipelineContext, create_pipeline
    from plan_agent import PlanAgent, Proposal
    from agent import ReviewAgent
    import search_grounding
    
    # Set up offline search backend
    FAKE_PACK = {
        "https://arxiv.org/abs/2607.13104": "Self-Improvements in Modern Agentic Systems",
        "https://github.com/affaan-m/ECC": "ECC framework",
    }
    search_grounding.set_search_backend(lambda q: [
        {"title": t, "url": u} for u, t in FAKE_PACK.items()
    ])
    
    # Create backbone
    db = Path(__file__).resolve().parent.parent / "data" / "code_test.db"
    bb = Backbone(db)
    
    job_id = "job-code-001"
    spec = "Discover NEW experts/sources and propose novel improvements."
    
    # Lock spec and run Review -> Plan
    bb.lock_job_spec(job_id, spec)
    review_agent = ReviewAgent(bb)
    recs = review_agent.run(job_id)
    
    plan_agent = PlanAgent(bb)
    ctx = PipelineContext(job_id=job_id, review_recommendations=recs)
    proposals = plan_agent.run(job_id, ctx)
    
    print(f"Plan produced {len(proposals)} proposals")
    
    # Update context with proposals
    ctx.plan_proposals = proposals
    
    # Create and run Code agent
    code_agent = CodeAgent(bb)
    try:
        changes = code_agent.run(job_id, ctx)
        print(f"\nCode generated {len(changes)} changes:")
        for c in changes:
            print(f"  - {c.change_type}: {c.file_path} ({c.estimated_lines} lines)")
    except RuntimeError as e:
        print(f"\nCode generation failed: {e}")
    
    # Verify chain
    ok, broken = bb.verify_chain()
    print(f"\nChain: {'OK' if ok else f'BROKEN at {broken}'}")
    
    bb.close()
