"""
plan_agent.py — Plan role for self-improving agent system.
==========================================================

DESIGN:
  - Takes Review's accepted recommendations (with scores) as input
  - Transforms recommendations into concrete, actionable proposals
  - Proposals are: change_type, summary, description, priority, estimated_effort
  - Priority derived from: recommendation priority + scores (novelty, relevance, etc.)
  - All proposals written to change board as change_type="proposal"
  - Fail-closed: if no valid recommendations, raises before proposing

CONTRACT:
  Input: PipelineContext with review_recommendations (list of Recommendation objects)
  Output: list of Proposal objects for the pipeline context
  
  Each Proposal becomes a change board entry that Code role can consume.

KEDB considerations:
  - Model may invent proposal types -> constrain at parser boundary
  - Model may over/under-estimate effort -> use conservative defaults
  - Empty input -> fail-closed (no proposals generated)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backbone import Backbone
    from pipeline import PipelineContext


# ---------------------------------------------------------------- constants

# Valid proposal types (constrain at parser boundary)
PROPOSAL_TYPES = (
    "feature",           # New functionality
    "bugfix",            # Fixes a defect
    "refactor",          # Code restructuring without behavior change
    "test",              # New or improved tests
    "docs",              # Documentation improvements
    "infrastructure",    # Build, CI, deployment improvements
    "research",          # Exploratory work, spikes
)

# Default effort estimates (in arbitrary units, e.g., hours or story points)
EFFORT_DEFAULT = 5
EFFORT_RANGE = {
    "low": 2,
    "medium": 5,
    "high": 8,
}

# Priority calculation weights
SCORE_WEIGHTS = {
    "novelty": 0.3,
    "relevance": 0.3,
    "evidence_quality": 0.2,
    "actionability": 0.15,
    "vision_alignment": 0.05,
}


@dataclass
class Proposal:
    """A concrete proposal generated by the Plan role."""
    # What to change
    change_type: str
    summary: str
    description: str
    
    # Why (from Review recommendation)
    source: str
    evidence: str
    impact: str
    risk: str
    recommendation_type: str  # original review type
    
    # Priority and effort
    priority: float
    estimated_effort: int
    
    # Metadata
    recommendation_id: str | None = None  # reference to source recommendation
    model_proposal_type: str = ""  # original type word from model (pre-normalisation)
    scores: dict = field(default_factory=dict)  # inherited from recommendation
    
    # For change board
    def to_change_payload(self) -> dict:
        """Convert to payload format for change board."""
        return {
            "change_type": self.change_type,
            "summary": self.summary,
            "description": self.description,
            "source": self.source,
            "evidence": self.evidence,
            "impact": self.impact,
            "risk": self.risk,
            "recommendation_type": self.recommendation_type,
            "priority": self.priority,
            "estimated_effort": self.estimated_effort,
            "scores": self.scores,
            "model_proposal_type": self.model_proposal_type,
        }


# Synonym mapping for proposal types (constrain at parser boundary)
PROPOSAL_TYPE_SYNONYMS = {
    "feature": "feature",
    "new_feature": "feature",
    "enhancement": "feature",
    "improvement": "feature",
    
    "bugfix": "bugfix",
    "bug_fix": "bugfix",
    "fix": "bugfix",
    "patch": "bugfix",
    
    "refactor": "refactor",
    "refactoring": "refactor",
    "restructure": "refactor",
    "cleanup": "refactor",
    
    "test": "test",
    "tests": "test",
    "testing": "test",
    "unit_test": "test",
    "integration_test": "test",
    
    "docs": "docs",
    "documentation": "docs",
    "doc": "docs",
    
    "infrastructure": "infrastructure",
    "infra": "infrastructure",
    "ci": "infrastructure",
    "build": "infrastructure",
    "deployment": "infrastructure",
    
    "research": "research",
    "spike": "research",
    "investigation": "research",
    "exploration": "research",
}


# ---------------------------------------------------------------- normalisation

def normalise_proposal_type(raw_type: str) -> tuple[str, bool]:
    """Map a model-produced proposal type onto a canonical type.
    
    Returns (canonical_type, was_recognised).
    Unknown types fall back to 'refactor' (middle-priority, conservative).
    """
    import re
    key = re.sub(r"[^a-z_]", "", (raw_type or "").strip().lower())
    if key in PROPOSAL_TYPE_SYNONYMS:
        return PROPOSAL_TYPE_SYNONYMS[key], True
    return "refactor", False


# ---------------------------------------------------------------- the agent

class PlanAgent:
    """Plan role: transforms Review recommendations into concrete proposals.
    
    All actions flow through the Backbone's audited API.
    Fail-closed: empty or invalid input raises before proposing.
    """

    def __init__(self, bb: "Backbone", role: str = "plan"):
        self.bb = bb
        self.role = role
        self.model = None  # Plan role currently uses deterministic logic, no LLM
        # In future: could use LLM for creative proposal generation
        # For now: deterministic transformation of recommendations

    def run(self, job_id: str, context: "PipelineContext") -> list[Proposal]:
        """Transform Review recommendations into Plan proposals.
        
        Args:
            job_id: The job identifier
            context: PipelineContext containing review_recommendations
            
        Returns:
            List of Proposal objects
            
        Raises:
            RuntimeError: If no valid recommendations to transform
        """
        import hashlib
        
        # 1. Goal-drift guard: spec re-injected verbatim at handoff (traced by pipeline)
        #    The pipeline orchestrator calls inject_spec before invoking us.
        #    We just need to get the spec for any direct calls.
        spec = self.bb.get_spec_verbatim(job_id)
        
        # 2. Extract recommendations from context
        recs = context.review_recommendations if context else []
        
        # 3. Fail-closed: no recommendations = no proposals
        if not recs:
            self.bb.trace("tool_call", self.role, {
                "tool": "plan_validation",
                "status": "empty_input_abort",
                "detail": "no review recommendations to transform — aborting",
            }, job_id=job_id)
            raise RuntimeError("Plan role: no review recommendations to transform")
        
        # 4. Trace the plan invocation with input summary
        self.bb.trace("role_invoke", self.role, {
            "input_type": "review_recommendations",
            "input_count": len(recs),
            "scored_count": sum(1 for r in recs if hasattr(r, 'scores') and r.scores),
            "spec_sha256_tail": hashlib.sha256(spec.encode()).hexdigest()[-12:],
        }, job_id=job_id)
        
        # 5. Transform each recommendation into proposal(s)
        proposals = []
        for i, rec in enumerate(recs):
            rec_proposals = self._transform_recommendation(rec, job_id, i)
            proposals.extend(rec_proposals)
            
            # Trace each transformation
            self.bb.trace("tool_call", self.role, {
                "tool": "recommendation_transform",
                "recommendation_idx": i,
                "recommendation_source": rec.source[:100] if hasattr(rec, 'source') else str(rec)[:100],
                "proposals_generated": len(rec_proposals),
            }, job_id=job_id)
        
        # 6. Fail-closed: if no proposals generated from valid recs
        if not proposals:
            self.bb.trace("tool_call", self.role, {
                "tool": "plan_validation",
                "status": "no_proposals_abort",
                "detail": f"{len(recs)} recommendations yielded 0 proposals",
            }, job_id=job_id)
            raise RuntimeError(f"Plan role: {len(recs)} recommendations yielded 0 proposals")
        
        # 7. Sort proposals by priority (descending)
        proposals.sort(key=lambda p: p.priority, reverse=True)
        
        # 8. Write all proposals to the change board
        for prop in proposals:
            change_id = self.bb.propose_change(
                job_id, self.role, "proposal",
                f"{prop.change_type}: {prop.summary}",
                prop.to_change_payload(),
                tier=3,
            )
            # Store change_id for reference
            prop.change_id = change_id
        
        # 9. Trace completion
        self.bb.trace("model_response", self.role, {
            "proposals_generated": len(proposals),
            "highest_priority": proposals[0].priority if proposals else 0,
            "total_effort_estimate": sum(p.estimated_effort for p in proposals),
        }, job_id=job_id)
        
        return proposals

    def _transform_recommendation(self, rec, job_id: str, rec_idx: int) -> list[Proposal]:
        """Transform a single Recommendation into one or more Proposal objects.
        
        Rules:
        - research_paper -> typically generates "research" or "feature" proposals
        - source_class -> typically generates "feature" proposals (integrate the source)
        - improvement_proposal -> typically generates "feature", "refactor", or "infrastructure"
        
        Each proposal inherits the recommendation's scores and metadata.
        """
        proposals = []
        
        # Extract fields from recommendation
        source = getattr(rec, 'source', '')
        evidence = getattr(rec, 'evidence', '')
        impact = getattr(rec, 'impact', '')
        risk = getattr(rec, 'risk', 'medium')
        rec_type = getattr(rec, 'type', 'improvement_proposal')
        scores = getattr(rec, 'scores', {})
        model_type = getattr(rec, 'model_type', '')
        
        # Calculate inherited priority from recommendation
        base_priority = getattr(rec, 'priority', 0)
        score_priority = self._calculate_score_priority(scores)
        combined_priority = base_priority + score_priority
        
        # Map recommendation type to typical proposal types
        if rec_type == "research_paper":
            # Research papers often lead to research or feature proposals
            proposals.append(Proposal(
                change_type="research",
                summary=f"Research: {evidence[:80]}",
                description=f"Investigate the approach described in '{evidence}'. "
                           f"Source: {source}. Impact: {impact}",
                source=source,
                evidence=evidence,
                impact=impact,
                risk=risk,
                recommendation_type=rec_type,
                priority=combined_priority,
                estimated_effort=EFFORT_RANGE.get(risk, EFFORT_DEFAULT),
                recommendation_id=f"rec-{rec_idx}",
                model_proposal_type="",
                scores=scores.copy() if scores else {},
            ))
            
            # Also consider a feature proposal if impact is high
            if score_priority > 2.5:
                proposals.append(Proposal(
                    change_type="feature",
                    summary=f"Implement: {evidence[:80]}",
                    description=f"Implement the approach from '{evidence}'. "
                               f"Source: {source}. Expected impact: {impact}",
                    source=source,
                    evidence=evidence,
                    impact=impact,
                    risk=risk,
                    recommendation_type=rec_type,
                    priority=combined_priority - 0.5,  # Slightly lower than research
                    estimated_effort=EFFORT_RANGE.get(risk, EFFORT_DEFAULT) * 2,
                    recommendation_id=f"rec-{rec_idx}",
                    model_proposal_type="",
                    scores=scores.copy() if scores else {},
                ))
                
        elif rec_type == "source_class":
            # Source classes typically lead to integration proposals
            proposals.append(Proposal(
                change_type="feature",
                summary=f"Integrate: {evidence[:80]}",
                description=f"Integrate the source class from {source}. "
                           f"Evidence: {evidence}. Impact: {impact}",
                source=source,
                evidence=evidence,
                impact=impact,
                risk=risk,
                recommendation_type=rec_type,
                priority=combined_priority,
                estimated_effort=EFFORT_RANGE.get(risk, EFFORT_DEFAULT) * 3,
                recommendation_id=f"rec-{rec_idx}",
                model_proposal_type="",
                scores=scores.copy() if scores else {},
            ))
            
        elif rec_type == "improvement_proposal":
            # Improvement proposals can map to various change types
            # Use the impact description to infer the best type
            impact_lower = impact.lower()
            
            if any(word in impact_lower for word in ['gui', 'ux', 'interface', 'ui']):
                change_type = "feature"
                effort_multiplier = 2
            elif any(word in impact_lower for word in ['refactor', 'restructure', 'cleanup']):
                change_type = "refactor"
                effort_multiplier = 2
            elif any(word in impact_lower for word in ['test', 'testing', 'coverage']):
                change_type = "test"
                effort_multiplier = 1
            elif any(word in impact_lower for word in ['docs', 'documentation']):
                change_type = "docs"
                effort_multiplier = 1
            elif any(word in impact_lower for word in ['ci', 'build', 'deploy', 'infrastructure']):
                change_type = "infrastructure"
                effort_multiplier = 3
            else:
                change_type = "feature"
                effort_multiplier = 2
            
            proposals.append(Proposal(
                change_type=change_type,
                summary=f"Improve: {evidence[:80]}",
                description=f"Implement improvement: {evidence}. "
                           f"Source: {source}. Expected impact: {impact}",
                source=source,
                evidence=evidence,
                impact=impact,
                risk=risk,
                recommendation_type=rec_type,
                priority=combined_priority,
                estimated_effort=EFFORT_RANGE.get(risk, EFFORT_DEFAULT) * effort_multiplier,
                recommendation_id=f"rec-{rec_idx}",
                model_proposal_type="",
                scores=scores.copy() if scores else {},
            ))
        
        # Fallback: if we somehow got here with no proposals
        if not proposals:
            proposals.append(Proposal(
                change_type="refactor",
                summary=f"Address: {evidence[:80]}",
                description=f"Address the recommendation: {evidence}. "
                           f"Source: {source}. Impact: {impact}",
                source=source,
                evidence=evidence,
                impact=impact,
                risk=risk,
                recommendation_type=rec_type,
                priority=combined_priority,
                estimated_effort=EFFORT_DEFAULT,
                recommendation_id=f"rec-{rec_idx}",
                model_proposal_type="",
                scores=scores.copy() if scores else {},
            ))
        
        return proposals

    def _calculate_score_priority(self, scores: dict) -> float:
        """Calculate additional priority from rubric scores.
        
        Scores are 1-5. Weights defined in SCORE_WEIGHTS.
        Returns a float that can be added to the base priority.
        """
        if not scores:
            return 0.0
        
        total = 0.0
        for score_name, weight in SCORE_WEIGHTS.items():
            if score_name in scores:
                # Normalize score to 0-1 range (score-1)/4, then multiply by weight * max contribution
                normalized = (scores[score_name] - 1) / 4.0  # 0.0 to 1.0
                total += normalized * weight * 3.0  # Max contribution of 3.0 per score
        
        return total

    def score_proposal(self, change_id: int, rubric: dict, scorer: str) -> None:
        """Score a proposal on the change board (similar to ReviewAgent.score).
        
        Args:
            change_id: The change board ID of the proposal
            rubric: Dict of score_name -> score (1-5)
            scorer: Who is scoring (e.g., "human", "vibe")
        """
        import json
        
        assert all(1 <= v <= 5 for v in rubric.values()), "scores must be 1-5"
        
        # Get current payload
        row = self.bb.conn.execute(
            "SELECT payload FROM changes WHERE change_id=?", (change_id,)
        ).fetchone()
        if row is None:
            raise ValueError(f"no change {change_id}")
        
        payload = json.loads(row["payload"])
        payload["scores"] = {**rubric, "scorer": scorer}
        
        # Update the change
        self.bb.conn.execute(
            "UPDATE changes SET payload=? WHERE change_id=?",
            (json.dumps(payload, sort_keys=True, separators=(",", ":")), change_id),
        )
        self.bb.conn.commit()
        
        self.bb.trace("board_write", scorer,
                      {"action": "score_proposal", "change_id": change_id, "scores": rubric})


if __name__ == "__main__":
    # Quick smoke test
    from pathlib import Path
    from backbone import Backbone
    from pipeline import PipelineContext, create_pipeline
    from agent import ReviewAgent, Recommendation
    import search_grounding
    
    # Set up offline search backend
    FAKE_PACK = {
        "https://arxiv.org/abs/2607.13104": "Self-Improvements in Modern Agentic Systems",
        "https://github.com/affaan-m/ECC": "ECC framework",
    }
    search_grounding.set_search_backend(lambda q: [
        {"title": t, "url": u} for u, t in FAKE_PACK.items()
    ])
    
    # Create backbone and pipeline
    db = Path(__file__).resolve().parent.parent / "data" / "plan_test.db"
    bb = Backbone(db)
    
    job_id = "job-plan-001"
    spec = "Discover NEW experts/sources and propose novel improvements."
    
    # Lock spec and run Review
    bb.lock_job_spec(job_id, spec)
    review_agent = ReviewAgent(bb)
    recs = review_agent.run(job_id)
    
    print(f"Review produced {len(recs)} recommendations")
    for r in recs:
        print(f"  - {r.type}: {r.source} (priority: {r.priority})")
    
    # Create Plan agent and test transformation
    plan_agent = PlanAgent(bb)
    context = PipelineContext(job_id=job_id, review_recommendations=recs)
    
    try:
        proposals = plan_agent.run(job_id, context)
        print(f"\nPlan produced {len(proposals)} proposals")
        for p in proposals:
            print(f"  - {p.change_type}: {p.summary} (priority: {p.priority}, effort: {p.estimated_effort})")
    except RuntimeError as e:
        print(f"\nPlan failed: {e}")
    
    # Verify chain
    ok, broken = bb.verify_chain()
    print(f"\nChain: {'OK' if ok else f'BROKEN at {broken}'}")
    
    bb.close()
