"""
test_agent.py — Test role for self-improving agent system.
========================================================

DESIGN:
  - Validates code changes and proposals from previous roles
  - Runs deterministic tests where possible (no LLM for validation)
  - Produces test results with pass/fail/hold verdicts
  - All test runs logged to change board with test_run_count tracking
  - Fail-closed: validation failures block the pipeline

CONTRACT:
  Input: PipelineContext with code_changes or plan_proposals
  Output: list of TestResult objects
  
  Each TestResult is written to change board as change_type="test_result"
  and logged via Backbone.log_test_run() for counting.

KEDB considerations:
  - Model may fabricate test results -> constrain at parser boundary
  - Test re-roll trap: never re-run same test on same change
  - Empty input -> fail-closed (no tests to run)
  - Test never edits what it tests (AGENTS.md rule #5)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backbone import Backbone
    from pipeline import PipelineContext
    from plan_agent import Proposal


# ---------------------------------------------------------------- constants

# Valid test verdicts
VERDICTS = ("pass", "fail", "hold")

# Test categories for classification
TEST_CATEGORIES = (
    "unit",              # Unit tests for individual functions
    "integration",       # Integration tests for component interactions
    "regression",        # Regression tests for known issues
    "validation",        # Validation tests for input/output contracts
    "performance",       # Performance/load tests
    "security",          # Security tests
)

# Default test priorities by category
CATEGORY_PRIORITY = {
    "security": 5,
    "regression": 4,
    "integration": 3,
    "unit": 2,
    "validation": 2,
    "performance": 1,
}


@dataclass
class TestResult:
    """A test result generated by the Test role."""
    # What was tested
    test_name: str
    category: str
    description: str
    
    # The target being tested
    target_type: str  # "proposal" or "code_change"
    target_id: str  # reference to the proposal or code change
    target_summary: str
    
    # Result
    verdict: str  # "pass", "fail", "hold"
    detail: str
    
    # Metadata
    priority: int
    change_id: int | None = None  # change board ID for this test result
    
    def to_change_payload(self) -> dict:
        """Convert to payload format for change board."""
        return {
            "test_name": self.test_name,
            "category": self.category,
            "description": self.description,
            "target_type": self.target_type,
            "target_id": self.target_id,
            "target_summary": self.target_summary,
            "verdict": self.verdict,
            "detail": self.detail,
            "priority": self.priority,
        }


# ---------------------------------------------------------------- the agent

class TestAgent:
    """Test role: validates code changes and proposals.
    
    All actions flow through the Backbone's audited API.
    Fail-closed: validation failures raise before accepting.
    Test never edits what it tests (AGENTS.md rule #5).
    """

    def __init__(self, bb: "Backbone", role: str = "test"):
        self.bb = bb
        self.role = role
        self.model = None  # Test role uses deterministic validation, no LLM

    def run(self, job_id: str, context: "PipelineContext") -> list[TestResult]:
        """Validate code changes or proposals from previous roles.
        
        Args:
            job_id: The job identifier
            context: PipelineContext containing code_changes or plan_proposals
            
        Returns:
            List of TestResult objects
            
        Raises:
            RuntimeError: If no valid targets to test or validation fails
        """
        import hashlib
        
        # 1. Goal-drift guard: spec re-injected verbatim at handoff
        spec = self.bb.get_spec_verbatim(job_id)
        
        # 2. Determine what to test (prefer code_changes, fall back to plan_proposals)
        targets = self._get_test_targets(context)
        
        # 3. Fail-closed: no targets = no tests
        if not targets:
            self.bb.trace("tool_call", self.role, {
                "tool": "test_validation",
                "status": "empty_input_abort",
                "detail": "no code changes or proposals to test — aborting",
            }, job_id=job_id)
            raise RuntimeError("Test role: no code changes or proposals to test")
        
        # 4. Trace the test invocation
        self.bb.trace("role_invoke", self.role, {
            "input_type": "code_changes" if targets[0].get("target_type") == "code_change" else "plan_proposals",
            "input_count": len(targets),
            "spec_sha256_tail": hashlib.sha256(spec.encode()).hexdigest()[-12:],
        }, job_id=job_id)
        
        # 5. Validate each target
        results: list[TestResult] = []
        for target in targets:
            target_results = self._validate_target(target, job_id)
            results.extend(target_results)
            
            # Trace each validation
            for r in target_results:
                self.bb.trace("tool_call", self.role, {
                    "tool": "validation_test",
                    "target_id": r.target_id,
                    "test_name": r.test_name,
                    "verdict": r.verdict,
                }, job_id=job_id)
        
        # 6. Fail-closed: if any critical test failed
        critical_failures = [r for r in results if r.priority >= 4 and r.verdict == "fail"]
        if critical_failures:
            self.bb.trace("tool_call", self.role, {
                "tool": "test_validation",
                "status": "critical_failure_abort",
                "failure_count": len(critical_failures),
                "details": [f"{r.test_name}: {r.detail}" for r in critical_failures[:3]],
            }, job_id=job_id)
            raise RuntimeError(
                f"Test role: {len(critical_failures)} critical test(s) failed; "
                f"aborting pipeline"
            )
        
        # 7. Write all test results to the change board
        for result in results:
            change_id = self.bb.propose_change(
                job_id, self.role, "test_result",
                f"{result.verdict.upper()}: {result.test_name}",
                result.to_change_payload(),
                tier=3,
            )
            result.change_id = change_id
            
            # Also log to test_runs table for counting
            self.bb.log_test_run(change_id, result.verdict, result.detail)
        
        # 8. Trace completion
        self.bb.trace("model_response", self.role, {
            "tests_run": len(results),
            "passed": len([r for r in results if r.verdict == "pass"]),
            "failed": len([r for r in results if r.verdict == "fail"]),
            "held": len([r for r in results if r.verdict == "hold"]),
        }, job_id=job_id)
        
        return results

    def _get_test_targets(self, context: "PipelineContext") -> list[dict]:
        """Extract testable targets from pipeline context.
        
        Prioritizes code_changes, falls back to plan_proposals.
        Returns list of dicts with keys: target_type, target_id, target_summary, raw_obj
        """
        targets = []
        
        # First, try code changes
        if context.code_changes:
            for i, change in enumerate(context.code_changes):
                # Handle both dict and CodeChange objects
                if isinstance(change, dict):
                    summary = change.get("summary", change.get("description", ""))
                else:
                    # CodeChange object
                    summary = getattr(change, "summary", "") or \
                             getattr(change, "proposal_summary", "") or \
                             f"{change.change_type}: {change.file_path}"
                targets.append({
                    "target_type": "code_change",
                    "target_id": f"code-{i}",
                    "target_summary": str(summary)[:100],
                    "raw_obj": change,
                })
        
        # Fall back to plan proposals
        if not targets and context.plan_proposals:
            for i, prop in enumerate(context.plan_proposals):
                # Handle both dict and Proposal objects
                if isinstance(prop, dict):
                    summary = prop.get("summary", prop.get("description", ""))[:100]
                else:
                    summary = getattr(prop, "summary", "")[:100]
                targets.append({
                    "target_type": "proposal",
                    "target_id": f"prop-{i}",
                    "target_summary": summary,
                    "raw_obj": prop,
                })
        
        return targets

    def _validate_target(self, target: dict, job_id: str) -> list[TestResult]:
        """Run validation tests against a single target.
        
        Generates deterministic test results based on the target's properties.
        """
        results = []
        target_type = target["target_type"]
        target_id = target["target_id"]
        target_summary = target["target_summary"]
        raw_obj = target["raw_obj"]
        
        # Extract fields based on target type
        if target_type == "proposal":
            # For proposals, validate structure and content
            change_type = ""
            description = ""
            if isinstance(raw_obj, dict):
                change_type = raw_obj.get("change_type", "")
                description = raw_obj.get("description", "")
            else:
                change_type = getattr(raw_obj, "change_type", "")
                description = getattr(raw_obj, "description", "")
            
            # Test 1: Proposal has valid change_type
            results.append(self._run_test(
                test_name="validate_change_type",
                category="validation",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                test_fn=lambda: self._validate_change_type(change_type),
            ))
            
            # Test 2: Proposal has non-empty description
            results.append(self._run_test(
                test_name="validate_description",
                category="validation",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                test_fn=lambda: self._validate_non_empty(description, "description"),
            ))
            
            # Test 3: Proposal has reasonable effort estimate
            effort = 0
            if isinstance(raw_obj, dict):
                effort = raw_obj.get("estimated_effort", 0)
            else:
                effort = getattr(raw_obj, "estimated_effort", 0)
            results.append(self._run_test(
                test_name="validate_effort_estimate",
                category="validation",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                test_fn=lambda: self._validate_effort(effort),
            ))
            
            # Test 4: Proposal priority is within expected range
            priority = 0
            if isinstance(raw_obj, dict):
                priority = raw_obj.get("priority", 0)
            else:
                priority = getattr(raw_obj, "priority", 0)
            results.append(self._run_test(
                test_name="validate_priority_range",
                category="validation",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                test_fn=lambda: self._validate_priority(priority),
            ))
            
        # Always check for secrets regardless of target type
        results.append(self._run_test(
            test_name="validate_no_secrets",
            category="security",
            target_type=target_type,
            target_id=target_id,
            target_summary=target_summary,
            test_fn=lambda: self._validate_no_secrets(raw_obj),
        ))
        
        if target_type == "code_change":
            # For code changes, validate structure
            # These are placeholder tests - real code validation would go here
            results.append(self._run_test(
                test_name="validate_code_structure",
                category="unit",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                test_fn=lambda: (True, "Code structure looks valid"),
            ))
        
        return results

    def _run_test(self, test_name: str, category: str, target_type: str, 
                  target_id: str, target_summary: str, test_fn) -> TestResult:
        """Run a single test and return a TestResult.
        
        test_fn should return (success: bool, detail: str)
        """
        try:
            success, detail = test_fn()
            verdict = "pass" if success else "fail"
            
            # Security tests are highest priority
            if category == "security":
                priority = 5
            else:
                priority = CATEGORY_PRIORITY.get(category, 2)
            
            return TestResult(
                test_name=test_name,
                category=category,
                description=f"Test {category}: {test_name}",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                verdict=verdict,
                detail=detail,
                priority=priority,
            )
        except Exception as e:
            return TestResult(
                test_name=test_name,
                category=category,
                description=f"Test {category}: {test_name}",
                target_type=target_type,
                target_id=target_id,
                target_summary=target_summary,
                verdict="fail",
                detail=f"Test error: {str(e)}",
                priority=CATEGORY_PRIORITY.get(category, 2),
            )

    def _validate_change_type(self, change_type: str) -> tuple[bool, str]:
        """Validate that change_type is one of the known proposal types."""
        from plan_agent import PROPOSAL_TYPES
        if change_type in PROPOSAL_TYPES:
            return True, f"Valid change_type: {change_type}"
        return False, f"Unknown change_type: {change_type}. Must be one of {PROPOSAL_TYPES}"

    def _validate_non_empty(self, value: str, field_name: str) -> tuple[bool, str]:
        """Validate that a field is non-empty."""
        if value and value.strip():
            return True, f"{field_name} is present and non-empty"
        return False, f"{field_name} is empty or missing"

    def _validate_effort(self, effort: int | float) -> tuple[bool, str]:
        """Validate that effort estimate is reasonable."""
        if isinstance(effort, (int, float)) and 0 < effort <= 20:
            return True, f"Effort estimate {effort} is within valid range (1-20)"
        return False, f"Effort estimate {effort} is out of range (must be 1-20)"

    def _validate_priority(self, priority: float) -> tuple[bool, str]:
        """Validate that priority is within expected range."""
        if isinstance(priority, (int, float)) and -5 <= priority <= 10:
            return True, f"Priority {priority} is within valid range"
        return False, f"Priority {priority} is out of expected range (-5 to 10)"

    def _validate_no_secrets(self, obj) -> tuple[bool, str]:
        """Validate that no secrets are present in the object."""
        import json
        import os
        
        # Get API key for comparison (never stored in the check)
        api_key = os.environ.get("MISTRAL_API_KEY", "")
        
        # Convert obj to string for searching
        obj_str = ""
        try:
            if isinstance(obj, dict):
                obj_str = json.dumps(obj)
            else:
                obj_str = str(obj)
        except Exception:
            obj_str = str(obj)
        
        # Check for common secret patterns
        secret_patterns = [
            "api_key",
            "secret",
            "password",
            "token",
            "private_key",
        ]
        
        found_secrets = []
        for pattern in secret_patterns:
            if pattern in obj_str.lower():
                found_secrets.append(pattern)
        
        if found_secrets:
            return False, f"Potential secrets detected: {', '.join(found_secrets)}"
        
        # Check for actual API key
        if api_key and api_key in obj_str:
            return False, "API key detected in object"
        
        return True, "No secrets detected"

    def score_test(self, change_id: int, rubric: dict, scorer: str) -> None:
        """Score a test result on the change board.
        
        Args:
            change_id: The change board ID of the test result
            rubric: Dict of score_name -> score (1-5)
            scorer: Who is scoring (e.g., "human", "vibe")
        """
        import json
        
        assert all(1 <= v <= 5 for v in rubric.values()), "scores must be 1-5"
        
        # Get current payload
        row = self.bb.conn.execute(
            "SELECT payload FROM changes WHERE change_id=?", (change_id,)
        ).fetchone()
        if row is None:
            raise ValueError(f"no change {change_id}")
        
        payload = json.loads(row["payload"])
        payload["scores"] = {**rubric, "scorer": scorer}
        
        # Update the change
        self.bb.conn.execute(
            "UPDATE changes SET payload=? WHERE change_id=?",
            (json.dumps(payload, sort_keys=True, separators=(",", ":")), change_id),
        )
        self.bb.conn.commit()
        
        self.bb.trace("board_write", scorer,
                      {"action": "score_test", "change_id": change_id, "scores": rubric})


if __name__ == "__main__":
    # Quick smoke test
    from pathlib import Path
    from backbone import Backbone
    from pipeline import PipelineContext, create_pipeline
    from plan_agent import PlanAgent, Proposal
    from agent import ReviewAgent
    import search_grounding
    
    # Set up offline search backend
    FAKE_PACK = {
        "https://arxiv.org/abs/2607.13104": "Self-Improvements in Modern Agentic Systems",
        "https://github.com/affaan-m/ECC": "ECC framework",
    }
    search_grounding.set_search_backend(lambda q: [
        {"title": t, "url": u} for u, t in FAKE_PACK.items()
    ])
    
    # Create backbone
    db = Path(__file__).resolve().parent.parent / "data" / "test_test.db"
    bb = Backbone(db)
    
    job_id = "job-test-001"
    spec = "Discover NEW experts/sources and propose novel improvements."
    
    # Lock spec and run Review -> Plan
    bb.lock_job_spec(job_id, spec)
    review_agent = ReviewAgent(bb)
    recs = review_agent.run(job_id)
    
    plan_agent = PlanAgent(bb)
    ctx = PipelineContext(job_id=job_id, review_recommendations=recs)
    proposals = plan_agent.run(job_id, ctx)
    
    print(f"Plan produced {len(proposals)} proposals")
    
    # Update context with proposals
    ctx.plan_proposals = proposals
    
    # Create and run Test agent
    test_agent = TestAgent(bb)
    try:
        results = test_agent.run(job_id, ctx)
        print(f"\nTest produced {len(results)} results")
        for r in results:
            print(f"  - [{r.verdict.upper():5s}] {r.test_name:30s} (priority: {r.priority})")
            print(f"           {r.detail}")
    except RuntimeError as e:
        print(f"\nTest failed: {e}")
    
    # Verify chain
    ok, broken = bb.verify_chain()
    print(f"\nChain: {'OK' if ok else f'BROKEN at {broken}'}")
    
    bb.close()
